### PR TITLE
Fix shift modifier

### PR DESCRIPTION
**Pull request by ryanggrey**
When a keydown event is raised for `shift+3` we get something like:
```
{
  key: "£",
  code: "51" // this represents '3' and is therefore incorrect
}
```

When `keycode` parses the event it interprets this as "3" instead of "£". This results in us editing the element's value with "3" instead of correctly ignoring the key press. I'm guessing `keycode` is looking exclusively at `code` to return a key name (although I haven't checked their code). I don't think this is a bug in their lib as they're correctly interpreting the code. The event itself seems to have `key` and `code` that are inconsistent.

[The docs](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) state that keydown should not be used with `keyCode` and that keypress is better (I tested this and we get the correct code for "£" but `keycode` still fails to correctly interpret this for some reason). Also we can't use that as keypress only triggers for printable chars, but we want to handle unprintable keys like "Delete" etc. We could possibly listen to both events; keydown for special keys and keypress for regular keys, but this seemed to be adding complexity.

[Firefox docs ](https://developer.mozilla.org/en-US/docs/Web/Events/keydown) state that `event.key` is unimplemented in Firefox, but I tested use of `event.key` on macOS Chrome and Firefox and both work (we probably need to check these changes on Windows too). I also tested with all action types which revealed that `key` is sometimes different to `keycode`'s returned values, but we handle this by changing our action type names.

There may be some other good reasons that we're using `keycode` that I am not aware of, so please let me know if I've missed something.

### CODE REVIEW

**Comment by ryanggrey** [comment]
@rcassonScottLogic Could you pull this down and test on Windows please?

**Comment by oriondean** [comment]
Thanks for the detailed explanation

Some of the confusion around the keycode may be around the fact that pressing the shift key triggers a separate event from the '3' key

**Comment by ryanggrey** [comment]
I should add that the example event above is raised on keydown '3' while 'shift' is being held. Pressing 'shift' has already raised a previous event that has been correctly handled.

**Comment by rcassonScottLogic** [comment]
Works on IE11, Edge, Chrome and Firefox on Windows 10

**Pull request merged**
