### PR TITLE
Ensuring the caret is view able while entering long numbers

### PR DESCRIPTION
**Pull request by rcassonScottLogic**
this will enable the view able area of the text input to be scrolled to the position of the caret.

### CODE REVIEW

**Comment by rcassonScottLogic** [comment]
this should help fix #41.

the calculation isn't perfect. doesn't take into account different size characters. But it will keep the caret in view.

**Comment by chrisprice** [comment]
In a bid to keep as many features as possible out of finput (which I think is crucial for its long-term maintainability), could we see if this can be implemented using handlers outside of finput? If it can, then I propose we post the workaround on the issue and don't merge this PR.

**Comment by rcassonScottLogic** [comment]
i have created a codepen page that demonstrates this fix/workaround being issued from the client side code. 

https://codepen.io/rcassonScottLogic/pen/bRaPpX

**Comment by ryanggrey** [comment]
Workaround is preferred over this PR (as per @chrisprice comment) so closing this PR.

**Pull request closed without merging**
